### ISSUE TITLE
cluster config in separate core node

### ISSUE THREAD

**Issue by iscra** [vromero/activemq-artemis-helm#5]
Hi, very useful chart. I am using Artemis in a single node configuration for now (planning later for cluster), but I noticed that the possible cluster configuration is not correct. 

After some investigation found the change in ActiveMq Artemis 2.0:
https://github.com/apache/activemq-artemis/commit/0006627d120a9010f85aed16d8678e0a61073585

which adds xsi:schemaLocation="urn:activemq:core " to the core node, when the broker config is generated for the first time.

This causes the configure-cluster.sh to add separate "core" node in broker.xml, which is ignored by Artemis. The original schemaLocation contains also blank space at the end, which is probably unintended.

This can also break any other xml/xsl broker config added through override mechanism.

I have tried fixing the xml by adding the schema location, but in this case the broker refuses to start pointing to missing connector-ref. 

broker.xml contains in this case        
<core:connector-ref xmlns:core="urn:activemq:core">activemq-0</core:connector-ref>

so probably the explicit "core:connector-ref" is not recognised properly?

Not sure what the proper bugfix should be in this case.

**Comment by ferguardiola** [comment]
Yes, i've to change it too..

The error i got on start is that node-0 is not able to see node-1 

14:47:27,448 ERROR [org.apache.activemq.artemis.core.client] AMQ214016: Failed to create netty connection: java.net.UnknownHostException: jms-service-1.jms-service.default.svc.cluster.local
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280) [rt.jar:1.8.0_162]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) [rt.jar:1.8.0_162]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) [rt.jar:1.8.0_162]
	at java.net.InetAddress.getByName(InetAddress.java:1076) [rt.jar:1.8.0_162]
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:146) [netty-all-4.1.16.Final

Have you found any solution ?

**Comment by vromero** [comment]
I have made some changes and wrote some tests, this should be working now

**Comment by DanSalt** [comment]
This fix works great - thanks!  Unrelated (I can post somewhere else if needed) - do you have any plans to auto-expose your Prometheus integration via helm values.yaml? Just starting to think about how to create an aggregated dashboard for the cluster.

**Comment by vromero** [comment]
I'd love to, that's why I did the integration in the docker image. But now I need to do some more research, I have been mostly using influx lately and I'm working now in the usage of KUBEPING instead of static connections (there's a branch for it).

Feel free to tackle it or share any hint if you want.

**Comment by Fredrik-C** [comment]
I experienced the the issue: AMQ214016: Failed to create netty connection: java.net.UnknownHostException

When I tested with the chart in the KUBEPING branch it work fine! :)

**Comment by Amithpn** [comment]
Hi, im using the chart for replication 2 and i see the below error:
_Initialized artemis-plugin plugin
2019-05-20 09:10:29,869 ERROR [org.apache.activemq.artemis.core.client] AMQ214016: Failed to create netty connection: java.net.UnknownHostException: artemis-activemq-artemis-master-1.artemis-activemq-artemis-master.default.svc.cluster.local_

And both master nodea are failing with below exception:
_2019-05-20 12:48:20,792 ERROR [org.apache.activemq.artemis.core.server] AMQ224088: Timeout (10 seconds) while handshaking has occurred.
2019-05-20 12:48:30,791 ERROR [org.apache.activemq.artemis.core.server] AMQ224088: Timeout (10 seconds) while handshaking has occurred.
2019-05-20 12:48:40,791 ERROR [org.apache.activemq.artemis.core.server] AMQ224088: Timeout (10 seconds) while handshaking has occurred.
2019-05-20 12:48:50,792 ERROR [org.apache.activemq.artemis.core.server] AMQ224088: Timeout (10 seconds) while handshaking has occurred.
2019-05-20 12:49:00,791 ERROR [org.apache.activemq.artemis.core.server] AMQ224088: Timeout (10 seconds) while handshaking has occurred._

Can someone let me know the reason and how do i fix this?
